# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import main as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -2596
    var_0 = module_0.aa(int_0, int_0)
    assert var_0 == -5192
    var_1 = module_0.aa(int_0, int_0)
    assert var_1 == -5192
    module_1.object(**var_1)
