# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import main as module_0


def test_case_0():
    str_0 = 'UOM,xYI/uL"'
    var_0 = module_0.plus(str_0, str_0)
    assert var_0 == 'UOM,xYI/uL"UOM,xYI/uL"'
    assert module_0.a == 3
    assert module_0.b == 2
