# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import main as module_0


def test_case_0():
    list_0 = []
    var_0 = module_0.plus(list_0, list_0)
    assert module_0.a == 3
    assert module_0.b == 1
